#include <iostream>

using namespace std;



// echo like action

int main() {

  cout << "Hello World!";

  return 0;

}
#include <iostream>

using namespace std;



// echo like action

int main() {

  cout << "Zombie® Version 1.0";

  return 0;

}

#include <iostream>

using namespace std;



// echo like action

int main() {

  cout << "Copyright (c) 2021 Zombie® All rights reserved.";

  return 0;

}


